### ISSUE TITLE
Runtime error while inline is set to true.

### ISSUE THREAD

**Issue by pokhrelrewant** [anuzpandey/nepali-date-picker#1]
![image](https://github.com/anuzpandey/nepali-date-picker/assets/30952388/e3241f09-f091-4d07-9a5e-c895a7f1157a)

**Comment by anuzpandey** [comment]
Could you please provide me the snippet of your code.
From the response, I guess you are using an input element to view inline calendar. Now the inline feature is to show calendar as a widget only. If you need it to be a `picker` element. I will update it today and change the current implementation as widget.

If you need it as a widget only for now, use the following code.

```html
<div id="inline-calendar">
</div>
```


```javascript
<script>
    new NepaliDatePicker('#inline-calendar', {
        inline: true,
    })
</script>
```

**Comment by pokhrelrewant** [comment]
<div className="container">
                            <input id='date-picker' type="text" />     
                        </div>
                        
                        
                            new NepaliDatePicker('#date-picker', config)
                            
                            Here is the snippet.

**Comment by anuzpandey** [comment]
> ```
>                     <div className="container">
>                         <input id='date-picker' type="text" />     
>                     </div>
>                     
>                     
>                         new NepaliDatePicker('#date-picker', config)
>                         
>                         Here is the snippet. 
> ```

For this to work. Change the input element to a `div` block. and everything will work file.
To use it as picker, I will change the implementation.

I will update the documentation for now.

```html
<div className="container">
    <div id='date-picker' />     
</div>
```

**Comment by pokhrelrewant** [comment]
Thank you so much.

**Comment by pokhrelrewant** [comment]
How can I position the picker component just below the input field? Are only three options available (left, center, and right)?

**Comment by pokhrelrewant** [comment]
Great Work BTW.

**Comment by anuzpandey** [comment]
> Great Work BTW.

Thank you. If you need any more features. Please do tell. I am happy to add up new features along with other features that are TODO in readme.

**Comment by pokhrelrewant** [comment]
I am currently working on an electron-react app. I have forms for input and it is taking a little bit of time to load once I route to the page once I integrate the datepicker in an input field. For example, if I open the form, It opens only when the calendar loads which slightly reduces user experience. Is there any workaround to this that you happen to know? I will let you know if I come around it.

**Comment by anuzpandey** [comment]
@pokhrelrewant I think you will have to add it to build modules so that it doesnt load everytime on page load, if build modules are an option on React. I am not that familar with react now a days. Other solution could be LazyLoading the DatePicker Component.
I will try to reproduce it with Elector-React based app and get back to you soon.
