### ISSUE TITLE
Number of days in Month of year 2081 is not correct

### ISSUE THREAD

**Issue by novaprime-code** [anuzpandey/nepali-date-picker#3]
2081:[[31,31,32,32,31,30,30,30,29,30,30,30]  =>  this is incorrect 
it should be
2081 : [31, 32, 31, 32, 31, 30, 30, 30, 29, 30, 29, 31],

please check and update

**Comment by anuzpandey** [comment]
@novaprime-code Thank you for the update. Fix is on the way.
